apiVersion: sources.triggermesh.io/v1alpha1
kind: SalesforceSource
metadata:
  name: salesforce-source
  namespace: sfdc-to-redpanda
spec:
  subscription:
    channel: /data/ChangeEvents
    replayID: -2

  auth:
    clientID: <your consumer key, e.g. 3MVG9OvGYd.....>
    user: <your Salesforce user login email, e.g. bob2@amce.com>
    server: https://login.salesforce.com
    certKey:
      valueFromSecret:
        name: salesforce
        key: certKey
  sink:
    ref:
      apiVersion: eventing.triggermesh.io/v1alpha1
      kind: RedisBroker
      name: triggermesh-redis-broker