apiVersion: sources.triggermesh.io/v1alpha1
kind: SalesforceSource
metadata:
  name: salesforce-source
  namespace: sfdc-to-redpanda
spec:
  subscription:
    channel: /data/ChangeEvents
    replayID: -2

  auth:
    clientID: 3MVG9_kZcLde7U5rGnIkSry6Ck6shXQh40PbIfjhuQdGsELrUvJISQlnSwHGFJGqM_eXQoROtKmRgI65U9qTs
    user: jonathan2@triggermesh.com
    server: https://login.salesforce.com
    certKey:
      valueFromSecret:
        name: salesforce
        key: certKey
  sink:
    ref:
      apiVersion: eventing.triggermesh.io/v1alpha1
      kind: RedisBroker
      name: triggermesh-redis-broker