apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: approval-transformation
spec:
  context:
  - operation: store
    paths:
    - key: $type
      value: type
  - operation: add
    paths:
    - key: type
      value: approved.$type
  data:
  - operation: delete
    paths:
    - key: schema

---

apiVersion: eventing.triggermesh.io/v1alpha1
kind: Trigger
metadata:
  labels:
  name: broker-to-transformation
spec:
  filters:
    - all: 
      - exact:
          type: com.salesforce.stream.message
      - prefix:
          subject: Account/UPDATE
  broker:
    group: eventing.triggermesh.io
    kind: RedisBroker
    name: triggermesh-redis-broker
  target:
    ref:
      apiVersion: flow.triggermesh.io/v1alpha1
      kind: Transformation
      name: approval-transformation